// Orkestrate/src/components/chat/ChatInput.tsx
import { useState, useRef, type KeyboardEvent } from 'react';
import { Send, Plus, SlidersHorizontal, Telescope, Mic, X, Mail, HardDrive, Calendar } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ChatInputProps {
  onSend: (text: string) => void;
  disabled?: boolean;
  placeholder?: string;
  showAppsBanner?: boolean;
}

export function ChatInput({
  onSend,
  disabled = false,
  placeholder = 'Ask Orkestrate',
  showAppsBanner = true,
}: ChatInputProps) {
  const [value, setValue] = useState('');
  const [bannerDismissed, setBannerDismissed] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const handleSubmit = () => {
    if (!value.trim() || disabled) return;
    onSend(value.trim());
    setValue('');
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
    }
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleInput = () => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = `${Math.min(el.scrollHeight, 200)}px`;
  };

  const showBanner = showAppsBanner && !bannerDismissed;

  return (
    <div className="mx-auto w-full max-w-3xl px-4 pb-6 pt-2">
      {/* Outer card container — Littlebird-matched: visible border, clean white bg, subtle shadow */}
      <div className={cn(
        'rounded-[20px] border border-foreground/[0.07] bg-card shadow-lg shadow-foreground/[0.03] transition-all duration-300',
        showBanner ? 'pb-0' : ''
      )}>
        {/* Inner input area */}
        <div className="relative">
          <textarea
            ref={textareaRef}
            value={value}
            onChange={e => {
              setValue(e.target.value);
              handleInput();
            }}
            onKeyDown={handleKeyDown}
            placeholder={placeholder}
            rows={1}
            disabled={disabled}
            className={cn(
              'block w-full resize-none bg-transparent px-5 pt-5 pb-14 text-[15px] text-foreground',
              'placeholder:text-muted-foreground/60 focus:outline-none',
              'min-h-[100px] max-h-[240px] rounded-t-[20px]'
            )}
          />

          {/* Bottom control bar */}
          <div className="absolute bottom-0 left-0 right-0 flex items-center justify-between px-3 pb-3">
            {/* Action Group */}
            <div className="flex items-center gap-0.5">
              <button
                type="button"
                className="rounded-lg p-2 text-foreground/30 transition-all hover:bg-foreground/[0.05] hover:text-foreground/50 active:scale-95"
                title="Add attachment"
              >
                <Plus className="size-[18px]" />
              </button>
              <button
                type="button"
                className="rounded-lg p-2 text-foreground/30 transition-all hover:bg-foreground/[0.05] hover:text-foreground/50 active:scale-95"
                title="Reasoning mode"
              >
                <SlidersHorizontal className="size-[18px]" />
              </button>
              <button
                type="button"
                className="rounded-lg p-2 text-foreground/30 transition-all hover:bg-foreground/[0.05] hover:text-foreground/50 active:scale-95"
                title="Sources"
              >
                <Telescope className="size-[18px]" />
              </button>
            </div>

            {/* Submit Group */}
            <div className="flex items-center gap-1.5">
              <button
                type="button"
                className="rounded-lg p-2 text-foreground/30 transition-all hover:bg-foreground/[0.05] hover:text-foreground/50 active:scale-95"
                title="Voice input"
              >
                <Mic className="size-[18px]" />
              </button>
              <button
                type="button"
                onClick={handleSubmit}
                disabled={!value.trim() || disabled}
                className={cn(
                  'flex size-9 items-center justify-center rounded-full transition-all duration-200',
                  value.trim()
                    ? 'bg-foreground text-background shadow-sm hover:scale-105 active:scale-95'
                    : 'bg-foreground/8 text-foreground/20 cursor-not-allowed'
                )}
              >
                <Send className="size-4" />
              </button>
            </div>
          </div>
        </div>

        {/* Context banner — warm golden-tan strip like Littlebird */}
        {showBanner && (
          <div className="flex items-center justify-between px-5 py-2 border-t border-foreground/[0.04] bg-accent/50 rounded-b-[20px]">
            <span className="text-[12px] font-medium text-muted-foreground">
              Connect your apps to get better answers
            </span>
            <div className="flex items-center gap-3">
              <div className="flex -space-x-1">
                <div className="size-6 rounded-full border-2 border-card bg-red-500/10 flex items-center justify-center">
                   <Mail className="size-3 text-red-500/70" />
                </div>
                <div className="size-6 rounded-full border-2 border-card bg-amber-500/10 flex items-center justify-center">
                   <HardDrive className="size-3 text-amber-600/70" />
                </div>
                <div className="size-6 rounded-full border-2 border-card bg-blue-500/10 flex items-center justify-center">
                   <Calendar className="size-3 text-blue-500/70" />
                </div>
              </div>
              <button
                onClick={() => setBannerDismissed(true)}
                className="rounded-full p-1 text-foreground/25 transition-colors hover:bg-foreground/5 hover:text-foreground/50"
              >
                <X className="size-3.5" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// src/lib/components/ChatInput.svelte
<script lang="ts">
	import { fade } from "svelte/transition";
	import { SIIcon } from "@willingtonortiz/svelte-simple-icons";
	import { siGmail, siGoogledrive, siGooglecalendar } from "simple-icons";
	import {
		Plus,
		Mic,
		ArrowUp,
		SlidersHorizontal,
		Sparkles,
		X,
	} from "lucide-svelte";
	let {
		value = $bindable(""),
		placeholder = "Ask Orkestrate",
		onsend,
		compact = false,
		disabled = false,
	} = $props<{
		value?: string;
		placeholder?: string;
		onsend?: (msg: string) => void;
		compact?: boolean;
		disabled?: boolean;
	}>();
	let element: HTMLTextAreaElement;
	let showConnectBar = $state(true);
	function autoResize() {
		if (!element) return;
		element.style.height = "auto";
		element.style.height = Math.min(element.scrollHeight, 200) + "px";
	}
	function handleInput() {
		value = element.value;
		autoResize();
	}
	function handleKeydown(e: KeyboardEvent) {
		if (e.key === "Enter" && !e.shiftKey && !disabled) {
			e.preventDefault();
			send();
		}
	}
	function send() {
		if (disabled) return;
		const trimmed = value.trim();
		if (!trimmed) return;
		onsend?.(trimmed);
		value = "";
		if (element) {
			element.value = "";
			element.style.height = "auto";
		}
	}
	export function focus() {
		element?.focus();
	}
	$effect(() => {
		if (value === "" && element) {
			element.value = "";
			element.style.height = "auto";
		}
	});
</script>

<div class="w-full max-w-[760px] mx-auto">
	<!-- Unified Input Container -->
	<div
		class="relative flex flex-col bg-[var(--chat-input-bg)] rounded-2xl border border-[var(--chat-input-border)] transition-all duration-200"
	>
		<!-- Textarea -->
		<textarea
			bind:this={element}
			{placeholder}
			oninput={handleInput}
			onkeydown={handleKeydown}
			spellcheck="false"
			disabled={disabled}
			class="w-full bg-transparent border-none outline-none text-[var(--fg)] text-[var(--font-size-md)] leading-[1.5] tracking-[-0.01em] resize-none overflow-hidden px-4 pt-4 pb-2 placeholder:text-[#6B6B6B] selection:bg-white/10 disabled:opacity-50 disabled:cursor-not-allowed"
			style="min-height: 64px;"
		></textarea>
		<!-- Bottom Toolbar -->
		<div class="flex justify-between items-center px-4 pb-4 pt-1">
			<!-- Left tools: Bordered Chips -->
			<div class="flex items-center gap-2">
				<button
					class="p-2 rounded-lg border border-white/[0.06] bg-white/[0.02] text-[#8a8a8a] hover:text-[#e0e0e0] hover:bg-white/[0.05] transition-all duration-150"
					title="Attach"
				>
					<Plus size={18} strokeWidth={1.5} />
				</button>
				<button
					class="p-2 rounded-lg border border-white/[0.06] bg-white/[0.02] text-[#8a8a8a] hover:text-[#e0e0e0] hover:bg-white/[0.05] transition-all duration-150"
					title="Settings"
				>
					<SlidersHorizontal size={18} strokeWidth={1.5} />
				</button>
				<button
					class="p-2 rounded-lg border border-white/[0.06] bg-white/[0.02] text-[#8a8a8a] hover:text-[#e0e0e0] hover:bg-white/[0.05] transition-all duration-150"
					title="Enhance"
				>
					<Sparkles size={18} strokeWidth={1.5} />
				</button>
			</div>

			<!-- Right: Mic + Send -->
			<div class="flex items-center gap-3">
				<button
					class="p-1.5 rounded-lg text-[#8a8a8a] hover:text-[#e0e0e0] hover:bg-white/[0.05] transition-colors duration-150"
					title="Voice"
				>
					<Mic size={20} strokeWidth={1.5} />
				</button>

				<button
					onclick={send}
					disabled={disabled}
					class="w-10 h-10 flex items-center justify-center rounded-full bg-[#d0d0d0] text-[#121214] hover:bg-white transition-all duration-150 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
					title="Send message"
				>
					<ArrowUp size={22} strokeWidth={2.5} />
				</button>
			</div>
		</div>

		{#if showConnectBar && !compact}
			<div
				class="flex items-center justify-between px-5 py-3 border-t border-white/[0.04]"
				transition:fade={{ duration: 150 }}
			>
				<span
					class="text-[13px] font-normal text-[#8a8a8a] tracking-tight"
					>Connect your apps to get better answers</span
				>
				<div class="flex items-center gap-3">
					<!-- Brand Icons -->
					<div class="flex items-center gap-3.5">
						<SIIcon icon={siGmail} color="#EA4335" size={16} />
						<SIIcon
							icon={siGoogledrive}
							color="#4285F4"
							size={16}
						/>
						<SIIcon
							icon={siGooglecalendar}
							color="#FBBC04"
							size={16}
						/>
					</div>
					<button
						onclick={() => (showConnectBar = false)}
						class="p-0.5 rounded text-[#5a5a5a] hover:text-[#9a9a9a] transition-colors"
					>
						<X size={14} strokeWidth={2} />
					</button>
				</div>
			</div>
		{/if}
	</div>
</div>
